# Generated by Django 5.1.4 on 2025-07-09 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0002_remove_customised_section_last_section_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='first_message',
            field=models.TextField(default='this is first message', max_length=10000),
            preserve_default=False,
        ),
    ]
