# Generated by Django 5.1.4 on 2025-07-12 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0003_section_first_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.RemoveField(
            model_name='chapter',
            name='course',
        ),
        migrations.RemoveField(
            model_name='section',
            name='chapter',
        ),
        migrations.DeleteModel(
            name='ChatBot',
        ),
        migrations.RemoveField(
            model_name='user_course',
            name='course',
        ),
        migrations.RemoveField(
            model_name='customised_section',
            name='person_data',
        ),
        migrations.RemoveField(
            model_name='customised_section',
            name='section',
        ),
        migrations.RemoveField(
            model_name='eventsdetail',
            name='event',
        ),
        migrations.RemoveField(
            model_name='eventsdetail',
            name='person',
        ),
        migrations.RemoveField(
            model_name='person_content',
            name='person_data',
        ),
        migrations.RemoveField(
            model_name='person_content',
            name='section',
        ),
        migrations.RemoveField(
            model_name='person_questions',
            name='person_content',
        ),
        migrations.RemoveField(
            model_name='person_questions',
            name='person_data',
        ),
        migrations.RemoveField(
            model_name='user_course',
            name='last_section',
        ),
        migrations.RemoveField(
            model_name='user_course',
            name='user',
        ),
        migrations.DeleteModel(
            name='Chapter',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Customised_section',
        ),
        migrations.DeleteModel(
            name='Events',
        ),
        migrations.DeleteModel(
            name='EventsDetail',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.DeleteModel(
            name='Person_content',
        ),
        migrations.DeleteModel(
            name='Person_data',
        ),
        migrations.DeleteModel(
            name='Person_questions',
        ),
        migrations.DeleteModel(
            name='Section',
        ),
        migrations.DeleteModel(
            name='User_course',
        ),
    ]
