# Generated by Django 5.2.3 on 2025-07-18 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0004_delete_answer_remove_chapter_course_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='character',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='details',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='gender',
        ),
    ]
